{% set version = "1.0.1" %}

{% set python_min = python_min | default("3.9") %}

{% if 1 %}{% set jupyterlab = "jupyterlab >=4.2.0,<5" %}{% endif %}

package:
  name: jupyter-collaboration-ui
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-collaboration-ui/jupyter_collaboration_ui-{{ version }}.tar.gz
  sha256: 99f407ca9910a9dacae2d07021b810b7e2e94e954b26b3bb8f14a2443e49e5cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  number: 0

requirements:
  host:
    - {{ jupyterlab }}
    - hatch-jupyter-builder
    - hatchling >=1.4.0
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
  run_constrained:
    - {{ jupyterlab }}

test:
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}
  imports:
    - jupyter_collaboration_ui
  commands:
    - pip check
    # labextensions
    - jupyter labextension list
    # check
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "collaboration-extension.*OK" labextensions

about:
  home: https://github.com/jupyterlab/jupyter-collaboration
  summary: JupyterLab/Jupyter Notebook 7+ extension providing user interface integration for real time collaboration
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_collaboration_ui/labextension/static/third-party-licenses.json
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - conda-forge/jupyter-collaboration
    - bollwyvl
    # TODO: uncommment as PR #1 on
    # - conda-forge/jupyter-collaboration
