# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.0.0
  jupyterlab: jupyterlab >=4.4.0,<5

package:
  name: jupyter-collaboration-ui
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-collaboration-ui/jupyter_collaboration_ui-${{ version }}.tar.gz
  sha256: c6cc8cb266c5009b054ba0bc49c09b0e9b0b4076aa0da4fb376088cfe31b08bb

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - ${{ jupyterlab }}
    - hatch-jupyter-builder >=0.5
    - hatchling >=1.4.0
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
  run_constraints:
    - ${{ jupyterlab }}

tests:
  - python:
      imports: jupyter_collaboration_ui
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - jupyterlab
        - if: win
          then: m2-grep
        - python ${{ python_min }}
    script:
      - pip check
      - jupyter labextension list
      - jupyter labextension list 1>labextensions 2>&1
      - grep -iE "collaboration-extension.*OK" labextensions

about:
  summary: JupyterLab/Jupyter Notebook 7+ extension providing user interface integration for real time collaboration
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_collaboration_ui/labextension/static/third-party-licenses.json
  homepage: https://github.com/jupyterlab/jupyter-collaboration
  documentation: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - conda-forge/jupyter-collaboration
    - bollwyvl
