# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.2.0"
  jupyterlab_min: "4.4.0"
  jupyterlab_max: "5"
  python_check_max: "3.14"

package:
  name: jupyter-collaboration-ui
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-collaboration-ui/jupyter_collaboration_ui-${{ version }}.tar.gz
  sha256: 6501c1559ff2331584fa183c38b2334c1886761e71cbe0af8d5f525f25ea336d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - jupyterlab >=${{ jupyterlab_min }},<${{ jupyterlab_max }}
    - hatch-jupyter-builder >=0.5
    - hatchling >=1.4.0
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
  run_constraints:
    - jupyterlab >=${{ jupyterlab_min }},<${{ jupyterlab_max }}

tests:
  - python:
      imports: jupyter_collaboration_ui
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - jupyterlab
    script:
      - pip check
      - jupyter labextension list --debug
      - jupyter labextension list --debug 2>&1 | python -c "import re, sys; v = sys.stdin.read(); assert re.search(r'collaboration-extension.*OK', v)"

about:
  summary: JupyterLab/Jupyter Notebook 7+ extension providing user interface integration for real time collaboration
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_collaboration_ui/labextension/static/third-party-licenses.json
  homepage: https://github.com/jupyterlab/jupyter-collaboration
  documentation: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - conda-forge/jupyter-collaboration
    - bollwyvl
